// AUTO-GENERATED by scripts/init-auth-harness.sh — safe to edit, but
// re-running the installer with --force will overwrite it.
//
// White-box auth verification: boots the real app, reads the live
// FirebaseAuth state, and proves the sign-in surface is correct instead
// of guessing from a build exit code.
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:lumina/main.dart' as app;

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('auth smoke + live state probe', (tester) async {
    app.main();

    // Pump frames for a few seconds WITHOUT pumpAndSettle, which times out on
    // apps with perpetual animations (loading spinners, etc.).
    for (var i = 0; i < 24; i++) {
      await tester.pump(const Duration(milliseconds: 250));
    }

    // Best-effort screenshot (only saved when run via the screenshot driver).
    try {
      await binding.takeScreenshot('auth-01-launch');
    } catch (_) {/* no driver attached — assertions still run */}

    // ── White-box: read the REAL auth state from the running app ──
    final user = FirebaseAuth.instance.currentUser;
    final providers =
        user?.providerData.map((p) => p.providerId).toList() ?? const [];
    // verify-auth.sh greps this line out of the test output.
    debugPrint('VERIFY_AUTH currentUser=${user?.uid ?? "null"} '
        'providers=$providers');

    // Surface any exception captured during boot. takeException() consumes the
    // framework's pending exception cleanly — do NOT override FlutterError.onError
    // (that trips integration_test's own pending-exception guard).
    final bootError = tester.takeException();
    expect(bootError, isNull, reason: 'App threw during boot: $bootError');

    // When signed out, the sign-in screen MUST offer Apple (Guideline 4.8,
    // required because every app also offers Google).
    if (user == null) {
      final appleControl =
          find.textContaining(RegExp('apple', caseSensitive: false));
      expect(appleControl, findsWidgets,
          reason: 'Apple Sign-In control not found on the sign-in screen. '
              'App Store Guideline 4.8 requires it alongside Google.');
    }
  });
}
