import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:flutter/foundation.dart';

/// Initializes Firebase and configures Crashlytics + Analytics for any SSA app.
///
/// Each app passes its own [FirebaseOptions] (generated by FlutterFire CLI).
/// This replaces the duplicated Firebase.initializeApp + Crashlytics setup
/// that was copy-pasted across every app.
///
/// ```dart
/// // In main.dart:
/// await SSAFirebase.initialize(DefaultFirebaseOptions.currentPlatform);
/// ```
class SSAFirebase {
  SSAFirebase._();

  static FirebaseApp? _app;
  static FirebaseAnalytics? _analytics;

  /// Whether Firebase has been initialized.
  static bool get isInitialized => _app != null;

  /// The Firebase Analytics instance (available after [initialize]).
  static FirebaseAnalytics get analytics {
    assert(_analytics != null, 'Call SSAFirebase.initialize() first');
    return _analytics!;
  }

  /// Initialize Firebase with platform-specific options.
  ///
  /// Sets up Crashlytics to capture all Flutter errors and uncaught
  /// platform exceptions. Disables Crashlytics in debug mode.
  static Future<void> initialize(
    FirebaseOptions options, {
    bool enableCrashlyticsInDebug = false,
  }) async {
    if (_app != null) return; // Already initialized

    _app = await Firebase.initializeApp(options: options);
    _analytics = FirebaseAnalytics.instance;

    // Configure Crashlytics
    if (!kIsWeb) {
      final enableCrashlytics = kReleaseMode || enableCrashlyticsInDebug;
      await FirebaseCrashlytics.instance
          .setCrashlyticsCollectionEnabled(enableCrashlytics);

      if (enableCrashlytics) {
        // Capture Flutter framework errors
        FlutterError.onError =
            FirebaseCrashlytics.instance.recordFlutterFatalError;

        // Capture platform-level errors
        PlatformDispatcher.instance.onError = (error, stack) {
          FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
          return true;
        };
      }
    }
  }

  /// Log a custom event to Analytics.
  static Future<void> logEvent(
    String name, {
    Map<String, Object>? parameters,
  }) async {
    await _analytics?.logEvent(name: name, parameters: parameters);
  }

  /// Set the current user ID for Analytics and Crashlytics.
  static Future<void> setUserId(String? userId) async {
    await _analytics?.setUserId(id: userId);
    if (!kIsWeb) {
      await FirebaseCrashlytics.instance
          .setUserIdentifier(userId ?? '');
    }
  }
}
