// File generated by FlutterFire CLI.
// IMPORTANT: Replace with your actual Firebase configuration
// Run: flutterfire configure
// This will generate the proper configuration for your Firebase project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run flutterfire configure to set up Firebase for this platform.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run flutterfire configure to set up Firebase for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlcoU-6fVNwl2D3pI38eZVYA13pG-5iBg',
    appId: '1:213849135698:web:04acd823f2c798955fdd8b',
    messagingSenderId: '213849135698',
    projectId: 'lumina-sosmartapps',
    authDomain: 'lumina-sosmartapps.firebaseapp.com',
    storageBucket: 'lumina-sosmartapps.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase Web configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5OLkj0r4jyZ_xWks34ugN5p053_VonT4',
    appId: '1:213849135698:android:8eb40c0e7e60d0d05fdd8b',
    messagingSenderId: '213849135698',
    projectId: 'lumina-sosmartapps',
    storageBucket: 'lumina-sosmartapps.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase Android configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2P-5eACtYw7QokMxWkm3y2ymHHPMv16w',
    appId: '1:213849135698:ios:3d61a8f880aa42a35fdd8b',
    messagingSenderId: '213849135698',
    projectId: 'lumina-sosmartapps',
    storageBucket: 'lumina-sosmartapps.firebasestorage.app',
    iosBundleId: 'com.carecompanion.app',
  );

  // TODO: Replace with your actual Firebase iOS configuration

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2P-5eACtYw7QokMxWkm3y2ymHHPMv16w',
    appId: '1:213849135698:ios:3d61a8f880aa42a35fdd8b',
    messagingSenderId: '213849135698',
    projectId: 'lumina-sosmartapps',
    storageBucket: 'lumina-sosmartapps.firebasestorage.app',
    iosBundleId: 'com.carecompanion.app',
  );

  // TODO: Replace with your actual Firebase macOS configuration
}

/*
 * SETUP INSTRUCTIONS:
 *
 * 1. Create a Firebase project at https://console.firebase.google.com
 *
 * 2. Install FlutterFire CLI:
 *    dart pub global activate flutterfire_cli
 *
 * 3. Configure Firebase for your project:
 *    flutterfire configure
 *
 * 4. This will automatically generate proper firebase_options.dart
 *
 * 5. Enable these Firebase services in console:
 *    - Authentication (Email/Password and Phone)
 *    - Cloud Firestore
 *    - Cloud Storage
 *    - Cloud Messaging
 *
 * 6. Set up Firestore security rules (see firestore.rules file)
 *
 * 7. For iOS, update ios/Runner/Info.plist with:
 *    - NSLocationWhenInUseUsageDescription
 *    - NSLocationAlwaysAndWhenInUseUsageDescription
 *    - NSCameraUsageDescription
 *    - NSMicrophoneUsageDescription
 *
 * 8. For Android, update android/app/src/main/AndroidManifest.xml with:
 *    - ACCESS_FINE_LOCATION
 *    - ACCESS_COARSE_LOCATION
 *    - ACCESS_BACKGROUND_LOCATION
 *    - CAMERA
 *    - CALL_PHONE
 *    - VIBRATE
 */