// File generated by FlutterFire CLI.
// IMPORTANT: Replace with your actual Firebase configuration
// Run: flutterfire configure
// This will generate the proper configuration for your Firebase project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run flutterfire configure to set up Firebase for this platform.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run flutterfire configure to set up Firebase for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase Web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  // TODO: Replace with your actual Firebase Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  // TODO: Replace with your actual Firebase iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.caregiverApp',
  );

  // TODO: Replace with your actual Firebase macOS configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.caregiverApp.RunnerTests',
  );
}

/*
 * SETUP INSTRUCTIONS:
 *
 * 1. Create a Firebase project at https://console.firebase.google.com
 *
 * 2. Install FlutterFire CLI:
 *    dart pub global activate flutterfire_cli
 *
 * 3. Configure Firebase for your project:
 *    flutterfire configure
 *
 * 4. This will automatically generate proper firebase_options.dart
 *
 * 5. Enable these Firebase services in console:
 *    - Authentication (Email/Password and Phone)
 *    - Cloud Firestore
 *    - Cloud Storage
 *    - Cloud Messaging
 *
 * 6. Set up Firestore security rules (see firestore.rules file)
 *
 * 7. For iOS, update ios/Runner/Info.plist with:
 *    - NSLocationWhenInUseUsageDescription
 *    - NSLocationAlwaysAndWhenInUseUsageDescription
 *    - NSCameraUsageDescription
 *    - NSMicrophoneUsageDescription
 *
 * 8. For Android, update android/app/src/main/AndroidManifest.xml with:
 *    - ACCESS_FINE_LOCATION
 *    - ACCESS_COARSE_LOCATION
 *    - ACCESS_BACKGROUND_LOCATION
 *    - CAMERA
 *    - CALL_PHONE
 *    - VIBRATE
 */
