// AUTO-GENERATED by scripts/init-auth-harness.sh
// Saves screenshots taken via binding.takeScreenshot() to build/verify-auth/.
import 'dart:io';
import 'package:integration_test/integration_test_driver_extended.dart';

Future<void> main() async {
  await integrationDriver(
    onScreenshot: (String name, List<int> bytes, [Map<String, Object?>? args]) async {
      final dir = Directory('build/verify-auth');
      if (!dir.existsSync()) dir.createSync(recursive: true);
      final file = File('build/verify-auth/$name.png');
      file.writeAsBytesSync(bytes);
      return true;
    },
  );
}
